name = "day12-etc"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Day12Etc"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "Day12Etc"
